# ChessEngine/Cargo.toml

# The purpose of this file is to let the rust-analyzer know where to look

[workspace]
members = [
    "utilities/fenlib",
    "utilities/rust",
    "bots/botv1",
    "bots/botv2",
]