# ChessEngine/Cargo.toml

# The purpose of this file is to let the rust-analyzer know where to look

[workspace]
resolver = "3"
members = [
    "utilities/fenlib",
    "utilities/rust",
    "fenlib_old",
    "bots/botv1_1",
    "bots/botv1_2",
    "bots/botv2_1",
    "bots/botv2_2",
    "bots/bot",
]
