use crate::utils::*;

// This file contains the default information for a fen at the starting position

pub const BOARDS: [u64; 12] = [
    RANK_6,
    (WHITE_KINGSIDE_BIT << 1) | (WHITE_QUEENSIDE_BIT >> 1),
    (WHITE_KINGSIDE_BIT << 2) | (WHITE_QUEENSIDE_BIT >> 2),
    WHITE_KINGSIDE_BIT | WHITE_QUEENSIDE_BIT,
    WHITE_KING_BIT << 1,
    WHITE_KING_BIT,
    RANK_1,
    (BLACK_KINGSIDE_BIT << 1) | (BLACK_QUEENSIDE_BIT >> 1),
    (BLACK_KINGSIDE_BIT << 2) | (BLACK_QUEENSIDE_BIT >> 2),
    BLACK_KINGSIDE_BIT | BLACK_QUEENSIDE_BIT,
    BLACK_KING_BIT << 1,
    BLACK_KING_BIT,
];

pub const WHITE_TO_MOVE: bool = true;

pub const CASTLING: u8 = WHITE_KINGSIDE_INFO | WHITE_QUEENSIDE_INFO | BLACK_KINGSIDE_INFO | BLACK_QUEENSIDE_INFO;

pub const ENPASSANT: u64 = EMPTY;

pub const HALFMOVE: u16 = 0x0;

pub const FULLMOVE: u16 = 0x1;

pub const WHITE: u64 = RANK_6 | RANK_7;

pub const BLACK: u64 = RANK_0 | RANK_1;

pub const FULL: u64 = WHITE | BLACK;

pub const WHITE_ATTACK: u64 = RANK_5;

pub const BLACK_ATTACK: u64 = RANK_2;

pub const WHITE_CHECK: u64 = EMPTY;

pub const BLACK_CHECK: u64 = EMPTY;

pub const WHITE_PIN: u64 = EMPTY;

pub const BLACK_PIN: u64 = EMPTY;

pub const LEGAL_MOVES: [[u64; 3]; MAX_MOVES] = [
    [RANK_6 & FILE_0, RANK_5 & FILE_0, EMPTY],
    [RANK_6 & FILE_1, RANK_5 & FILE_1, EMPTY],
    [RANK_6 & FILE_2, RANK_5 & FILE_2, EMPTY],
    [RANK_6 & FILE_3, RANK_5 & FILE_3, EMPTY],
    [RANK_6 & FILE_4, RANK_5 & FILE_4, EMPTY],
    [RANK_6 & FILE_5, RANK_5 & FILE_5, EMPTY],
    [RANK_6 & FILE_6, RANK_5 & FILE_6, EMPTY],
    [RANK_6 & FILE_7, RANK_5 & FILE_7, EMPTY],

    [RANK_6 & FILE_0, RANK_4 & FILE_0, EMPTY],
    [RANK_6 & FILE_1, RANK_4 & FILE_1, EMPTY],
    [RANK_6 & FILE_2, RANK_4 & FILE_2, EMPTY],
    [RANK_6 & FILE_3, RANK_4 & FILE_3, EMPTY],
    [RANK_6 & FILE_4, RANK_4 & FILE_4, EMPTY],
    [RANK_6 & FILE_5, RANK_4 & FILE_5, EMPTY],
    [RANK_6 & FILE_6, RANK_4 & FILE_6, EMPTY],
    [RANK_6 & FILE_7, RANK_4 & FILE_7, EMPTY],

    [RANK_7 & FILE_1, RANK_5 & FILE_0, EMPTY],
    [RANK_7 & FILE_1, RANK_5 & FILE_2, EMPTY],
    [RANK_7 & FILE_6, RANK_5 & FILE_5, EMPTY],
    [RANK_7 & FILE_6, RANK_5 & FILE_7, EMPTY],

    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY],
];