[package]
name = "rust_utils"
version = "0.1.0"
edition = "2024"

[lib]
name = "rust_utils"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.25.0", features = ["extension-module"] }
fenlib = { path = "../fenlib" }
botv1_1 = { path = "../../bots/botv1_1" }
botv1_2 = { path = "../../bots/botv1_2" }
botv2_1 = { path = "../../bots/botv2_1" }
botv2_2 = { path = "../../bots/botv2_2" }
